services:
  asterisk:
    container_name: asterisk
    image: andrius/asterisk:latest
    ports:
      - '5060:5060/udp'
      - '5060:5060/tcp'
      - '5038:5038'
    volumes:
      - ./asterisk/config:/etc/asterisk
      - ./asterisk/logs:/var/log/asterisk
    environment:
      - ASTERISK_AMI_USERNAME=${ASTERISK_AMI_USERNAME}
      - ASTERISK_AMI_PASSWORD=${ASTERISK_AMI_PASSWORD}
    networks:
      - telecom-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - telecom-network

  postgres:
    container_name: postgres
    image: timescale/timescaledb:latest-pg16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=events,api
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
      - LC_CTYPE=en_US.utf8
      - LC_COLLATE=en_US.utf8
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data
    networks:
      - telecom-network

  events:
    container_name: events
    build:
      context: .
      dockerfile: apps/events/Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - asterisk
      - rabbitmq
      - postgres
    environment:
      - NODE_ENV=production
      - ASTERISK_HOST=asterisk
      - ASTERISK_AMI_PORT=5038
      - ASTERISK_AMI_USERNAME=${ASTERISK_AMI_USERNAME}
      - ASTERISK_AMI_PASSWORD=${ASTERISK_AMI_PASSWORD}
      - RABBIT_URL=amqp://rabbitmq:5672
      - RABBIT_QUEUE=${RABBIT_QUEUE}
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/events
    volumes:
      - ./apps/events/logs:/app/logs
    networks:
      - telecom-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/users
    volumes:
      - ./apps/api/logs:/app/logs
    networks:
      - telecom-network

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  telecom-network:
    driver: bridge
