services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - telecom
  tele:
    image: mlan/asterisk
    network_mode: bridge
    cap_add:
      - sys_ptrace
      - net_admin
      - net_raw
    ports:
      - '${SMS_PORT-8080}:${WEBSMSD_PORT:-80}'
      - '5060:5060/udp'
      - '5060:5060'
      - '5061:5061'
      - '10000-10099:10000-10099/udp'
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}
      - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
      - PULSE_SERVER=unix:/run/pulse/socket
      - PULSE_COOKIE=/run/pulse/cookie
      - WEBSMSD_PORT=${WEBSMSD_PORT-80}
    volumes:
      - tele-conf:/srv
      - ./pulse:/run/pulse:rshared
      - /etc/localtime:/etc/localtime:ro
    networks:
      - telecom

volumes:
  tele-conf:
networks:
  telecom:
    name: telecom
    driver: bridge
